
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.TbCustomer TbCustomer {get; }
    public demo.TbNeta TbNeta {get; }
    public demo.TbShari TbShari {get; }
    public demo.TbSource TbSource {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCustomer = new demo.TbCustomer(loader("demo_tbcustomer"));
        TbNeta = new demo.TbNeta(loader("demo_tbneta"));
        TbShari = new demo.TbShari(loader("demo_tbshari"));
        TbSource = new demo.TbSource(loader("demo_tbsource"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCustomer.ResolveRef(this);
        TbNeta.ResolveRef(this);
        TbShari.ResolveRef(this);
        TbSource.ResolveRef(this);
    }
}

}
