
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbCustomer : TbBase<demo.Customer>
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Customer> _dataMap;
    private readonly System.Collections.Generic.List<demo.Customer> _dataList;
    
    public TbCustomer(JSONNode _buf): base(_buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Customer>();
        _dataList = new System.Collections.Generic.List<demo.Customer>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Customer _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.Customer.DeserializeCustomer(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    protected override demo.Customer Deserialize(JSONNode _ele) => demo.Customer.DeserializeCustomer(_ele);
    protected override int GetId(demo.Customer item) => item.Id;
    protected override void ResolveRefItem(demo.Customer item, Tables tables) => item.ResolveRef(tables);

    public System.Collections.Generic.Dictionary<int, demo.Customer> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Customer> DataList => _dataList;

    public demo.Customer GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.Customer Get(int key) => _dataMap[key];
    public int GetCount() => _dataMap.Count;
    public demo.Customer this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

