
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbNeta : TbBase<demo.Neta>
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Neta> _dataMap;
    private readonly System.Collections.Generic.List<demo.Neta> _dataList;
    
    public TbNeta(JSONNode _buf) : base(_buf) 
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Neta>();
        _dataList = new System.Collections.Generic.List<demo.Neta>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Neta _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.Neta.DeserializeNeta(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    protected override demo.Neta Deserialize(JSONNode _ele) => demo.Neta.DeserializeNeta(_ele);
    protected override int GetId(demo.Neta item) => item.Id;
    protected override void ResolveRefItem(demo.Neta item, Tables tables) => item.ResolveRef(tables);
    
    public System.Collections.Generic.Dictionary<int, demo.Neta> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Neta> DataList => _dataList;

    public demo.Neta GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.Neta Get(int key) => _dataMap[key];
    public int GetCount() => _dataMap.Count;
    public demo.Neta this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

